version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      # 1.28.0 is the last google-java-format release supporting Java 17.
      - dependency-name: "com.google.googlejavaformat:google-java-format"
        versions: [">=1.29.0"]
  - package-ecosystem: "npm"
    directory: "magik-language-server/client-vscode"
    schedule:
      interval: monthly
  - package-ecosystem: "pip"
    directory: ".github/scripts"
    schedule:
      interval: "monthly"
