package nl.ramsolutions.sw.loadlist.analysis;

import com.sonar.sslr.api.AstNode;
import com.sonar.sslr.api.AstNodeType;
import com.sonar.sslr.api.Token;
import com.sonar.sslr.api.Trivia;
import nl.ramsolutions.sw.loadlist.api.LoadListGrammar;

/**
 * A {@link AstNode} tree walker with pre- and post-methods to iterate a parse tree. Note that this
 * is generated by the {@code generate_ast_walker.py} script, do not edit this file manually!
 */
public abstract class LoadListAstWalker {

  /** Walk children of node. */
  protected void walkChildren(final AstNode node) {
    for (final AstNode childNode : node.getChildren()) {
      this.walkAst(childNode);
    }
  }

  /** Walk trivia and tokens of node. */
  protected void walkTokens(final AstNode tokenNode) {
    // Assume there can be only one token.
    final Token token = tokenNode.getToken();
    token.getTrivia().forEach(this::walkTrivia);
    this.walkToken(token);
  }

  /**
   * Start walking the node. The pre- and post-methods are called upon tree traversal.
   *
   * @param node Node to start walking.
   */
  @SuppressWarnings({"java:S1479", "checkstyle:MethodLength"})
  public void walkAst(final AstNode node) {
    final AstNodeType nodeType = node.getType();
    if (!(nodeType instanceof LoadListGrammar value)) {
      this.walkTokens(node);
      return;
    }

    switch (value) {
      case LOAD_LIST:
        this.walkPreLoadList(node);
        this.walkChildren(node);
        this.walkPostLoadList(node);
        break;

      case FILE_ENTRY:
        this.walkPreFileEntry(node);
        this.walkChildren(node);
        this.walkPostFileEntry(node);
        break;

      case FILE_PATH:
        this.walkPreFilePath(node);
        this.walkChildren(node);
        this.walkPostFilePath(node);
        break;

      case NEWLINE:
        this.walkPreNewline(node);
        this.walkChildren(node);
        this.walkPostNewline(node);
        break;

      case COMMENT:
        this.walkPreComment(node);
        this.walkChildren(node);
        this.walkPostComment(node);
        break;

      case SYNTAX_ERROR:
        this.walkPreSyntaxError(node);
        this.walkChildren(node);
        this.walkPostSyntaxError(node);
        break;

      default:
        this.walkPreDefault(node);
        this.walkChildren(node);
        this.walkPostDefault(node);
        break;
    }
  }

  protected void walkPreLoadList(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostLoadList(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreFileEntry(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostFileEntry(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreFilePath(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostFilePath(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreNewline(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostNewline(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreComment(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostComment(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreSyntaxError(final AstNode node) {
    this.walkPreDefault(node);
  }

  protected void walkPostSyntaxError(final AstNode node) {
    this.walkPostDefault(node);
  }

  protected void walkPreDefault(final AstNode node) {
    // pass
  }

  protected void walkPostDefault(final AstNode node) {
    // pass
  }

  protected void walkToken(final Token token) {
    // pass
  }

  protected void walkTrivia(final Trivia trivia) {
    // pass
  }
}
