name: Publish checks to wiki
on:
  push:
    branches: [develop]
    paths:
      - .github/workflows/publish-checks-wiki.yml
      - .github/scripts/generate_checks_pages.py
      - magik-checks/src/main/resources/nl/ramsolutions/sw/sonar/l10n/*/rules/*.html
      - magik-checks/src/main/java/nl/ramsolutions/sw/checks/*/*Check.java
  pull_request:
    paths:
      - .github/workflows/publish-checks-wiki.yml
      - .github/scripts/generate_checks_pages.py
      - magik-checks/src/main/resources/nl/ramsolutions/sw/sonar/l10n/*/rules/*.html
      - magik-checks/src/main/java/nl/ramsolutions/sw/checks/*/*Check.java
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: |
          git clone https://github.com/StevenLooman/magik-tools.wiki.git wiki
          rm -rf wiki/checks
      - run: |
          pip install --only-binary :all: --require-hashes -r .github/scripts/requirements.txt
          python3 .github/scripts/generate_checks_pages.py
      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff  # v24
        with:
          globs: 'wiki/checks/*.md'
          fix: true
      - uses: Andrew-Chen-Wang/github-wiki-action@1bbb4280446f9630e8e21a18012cbacf3b0f992e  # v5
        if: ${{ github.event_name == 'push' && github.repository_owner == 'StevenLooman' }}
        with:
          path: wiki
          #dry-run: true
